name: Process and Update Submissions

on:
  push:
    branches:
      - master

jobs:
  process:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: List directory contents
      run: |
        ls -R
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run submission processing script
      run: |
        python docs/submissions.py
    
    - name: Commit changes
      run: |
        git add docs/submissions.md
        git commit -m "Update submissions.md with processed links" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



# name: Process and Update Submissions

# on:
#   push:
#     branches:
#       - master

# jobs:
#   process:
#     runs-on: ubuntu-latest

#     permissions:
#       contents: write

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: List directory contents
#       run: |
#         ls -R

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Run submission processing script
#       run: |
#         python docs/submissions.py

#     - name: Configure Git
#       run: |
#         git config --local user.email "sushantbagul074@gmail.com"
#         git config --local user.name "Sushant"

#     - name: Commit changes
#       run: |
#         git add docs/submissions.md
#         git commit -m "Update submissions.md with processed links" || echo "No changes to commit"
#         git push
#       env:
#         PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
